### ISSUE TITLE
Exit Notification For Exit Requests Initiated on ESS not Going Through

### ISSUE THREAD

**Issue by Adebukola** [Mandiklopper/UBA-HR-Queries-Issues#79]
As at November 17, 5 exit requests had been made by staff via ESS.  HRBPs of the staff did not get notification of these exits.  Note that previous ticket logged was for notification of final exit managed by the Exit Management team on X3 while this is for exit request from ESS.

**Comment by Mandiklopper** [comment]
@Adebukola, thanks.  Please list the employee codes of the 5 employees.

**Comment by Mandiklopper** [comment]
@Adebukola please reply with the employee codes

**Comment by Mandiklopper** [comment]
@roberteta please assist with getting these employee codes.

**Comment by Adebukola** [comment]
A08007
A07835
A08215
A11552
A22027

**Comment by Mandiklopper** [comment]
https://senseable.co.za/scp/tickets.php?id=199 - Not yet assigned.

**Comment by Mandiklopper** [comment]
Email sent by Robert:

Hello JW,

Please also urgently look into why there are no notifications being sent out for exit requests initiated via ESS. I believe this has been logged on GitHub

The request for A07835 has been approved by the HRBP team, but no notification was sent out to the staff supervisor to comment so it can be routed to the Exit Management team for final exit processing so that exit stakeholders will get notified to complete exit checklist.

Regards,

**Comment by Mandiklopper** [comment]
Completed by Pierre. Please retest.

**Comment by roberteta** [comment]
Confirmed as per Exit Request for A14109 &  A23361
